### PR TITLE
Fixes #1 and reset at exit

### LINKED ISSUE #1: Won't mount fuse system if a program is running
Hi,
I tried to mount my esp8266 to a folder. esp8266 has a line in boot.py that runs the main loop of my program. I checked your code, it does breaks the loop twice, then reboots and gets in the raw mode. It does restart the device but after restart, my code will run automatically. It should have break that too. I tried doing 'break break reboot break raw' but I guess micropython's boot procedure clears serial buffer, thus commands after reboot won't run at all.

Also, why do you reboot after each command?

### PR DESCRIPTION
**Pull request by Cediddi**
This fixes #1 as well as adds an atexit registration. This changes the behavior of reset method as it wasn't soft-resetting the board previously.

### CODE REVIEW

**Comment by nickzoic** [comment]
Thanks Cediddi ... it looks sensible, I'll test on Tuesday and pull.

**Comment by Cediddi** [comment]
The fix I sent earlier was a bad approach, so I updated my branch with the correct way of doing it. The problem I had was, I have a loop in main.py that should be broken and a startup routine in boot.py which should not be broken. Damien said, if we drop on raw repl and reboot, main.py shouldn't run at all.  micropython/micropython#2936

**Comment by Cediddi** [comment]
Also added/improved some features (reset, delay etc.)  and formatted the code.

**Comment by kalaomer** [comment]
It looks great!

**Comment by mjeveritt** [comment]
I think you might wanna rebase, perhaps?

**Comment by nickzoic** [comment]
(wow, sorry, I had alerts turned off for this project and hadn't noticed all this in here!  I'm looking at rebasing it now ...)

**Pull request merged**
